export const GET_QUESTIONS = 'GET_QUESTIONS'
export const POST_QUESTION = 'POST_QUESTION'
export const POST_TOKEN = 'POST_TOKEN'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_ANSWERS = 'GET_ANSWERS'
export const GET_ANSWER = 'GET_ANSWER'